runtime: nodejs
env: flex

# This sample incurs costs to run on the App Engine flexible environment.
# The settings below are to reduce costs during testing and are not appropriate
# for production use. For more information, see:
# https://cloud.google.com/appengine/docs/flexible/nodejs/configuring-your-app-with-app-yaml
# manual_scaling:
#   instances: 1
# handlers:
# - url: /.*
#   script: this field is required, but ignored
#   secure: always
# resources:
#   cpu: 1
#   memory_gb: 0.5
#   disk_size_gb: 10

# skip_files:
#   - ^node_modules/.*$

endpoints_api_service:
  # The following values are to be replaced by information from the output of
  # 'gcloud endpoints services deploy openapi-appengine.yaml' command.
  name: mcc-fall-2019-g25.appspot.com
  rollout_strategy: managed

